### ISSUE TITLE
Automatically Post to GitHub on Failure

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/second_curtain#15]
It'd be awesome to have this project automatically comment on the GitHub pull request with a link to the failures HTML page.

**Comment by orta** [comment]
This could be handled by Danger.

**Comment by orta** [comment]
Was easy to add: https://github.com/artsy/eigen/blob/4454d6bb595a4fcc0d491c75eed07e24cae52300/Dangerfile#L69-L73
