### ISSUE TITLE
Update to logic around deciding what snapshots to show

### ISSUE THREAD

**Issue by orta** [ashfurrow/second_curtain#28]
https://github.com/orta/Snapshots/commit/1eb3b3880b58910cc3c5109e6da97a6a19cbde98#diff-540fbd6334e0d2f5602d5e0ab469111bR74

Fixes this use case: https://github.com/orta/Snapshots/commit/1eb3b3880b58910cc3c5109e6da97a6a19cbde98#diff-3ee3a5b11f02a33f691495fc2633356cR17 - which is super common in most of our projects

**Comment by ashfurrow** [comment]
Cool.
