### ISSUE TITLE
Location of images vs location of index.html

### ISSUE THREAD

**Issue by larslockefeer** [ashfurrow/second_curtain#34]
While working in #33, I found that while the `index.html` ends up inside a folder, the images are not in the same folder but in the level above. As far as i understand, this means that the images of test *n* may be overwritten by the images of test *n + 1*. Is this the expected behaviour?

**Comment by ashfurrow** [comment]
Hmm, interesting. This could definitely present a problem, and it's not expected behaviour. I'll try and look into this this weekend.
