### ISSUE TITLE
suggestions for fastlane scan

### ISSUE THREAD

**Issue by gekitz** [ashfurrow/second_curtain#41]
Any suggestions on how to use this with fastlane scan?

**Comment by ashfurrow** [comment]
Hmm, good question. I've not used it with `scan` before, I don't think it's likely to work out of the box. The key would be getting the `xcodebuild` output into `second_curtain` somehow. It's possible `scan` writes the raw output to a log file? Maybe we could read that in and pipe it to `second_curtain`?

**Comment by larslockefeer** [comment]
Haven't used `scan` either, but the [readme](https://github.com/fastlane/fastlane/blob/master/scan/README.md) states that the raw output `xcodebuild` generates is written to `~/Library/Logs/scan`.

So maybe something along the lines of `cat ~/Library/Logs/scan/[logfile] | second_curtain` will do the trick?

I'm not sure about the format of the log files that `scan` puts there, but you'll want to use the file with the test output, as this contains the information that `second_curtain` needs.

**Comment by gekitz** [comment]
Thanks for all the input, in the end I took the a simpler solution. I used Travis's artifacts feature to upload all uncommited changes to S3. It's not as nice as the web preview with second_curtain, but it works good enough.
